id: IE2ABDE32
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T04:58:47+00:00'
last_modified: '2022-06-07T20:33:33.003704+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ6641
  title: རྒྱལ་སྲས་ཐོགས་མེད་ཀྱི་བཀའ་འབུམ་ཐོར་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B004:
      image_group_id: I1KG1595
      title: ''
      total_pages: 436
      order: 1
      base_file: B004.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
