id: IE2ABDE32
legacy_id: P004142
ocr_import_info:
  bdrc_scan_id: W2CZ6641
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T04:56:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:14:49.536115+00:00'
last_modified: 2022-09-02 23:15:39.067011
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ6641
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ6641
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱལ་སྲས་ཐོགས་མེད་ཀྱི་བཀའ་འབུམ་ཐོར་བུ།
  author: དཔལ་ལྡན་ཡེ་ཤེས།
statistics:
  ocr_word_mean_confidence_index: 0.7229245316545152
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1KG1595:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1595
      total_pages: 436
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1595.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7229245316545152
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
