id: P004142
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ6641
  title: རྒྱལ་སྲས་ཐོགས་མེད་ཀྱི་བཀའ་འབུམ་ཐོར་བུ།
  author: ''
  volumes:
    6a1b7a013c3d41d099b2570cf4575b1f:
      image_group_id: I1KG1595
      title: ''
      volume_number: 1
      total_pages: 436
      base_file: v001.txt
